DATASET_PATH: ./data/code_blocks_regex_graph_v4.csv
label: '[''import'', ''data_import'', ''data_export'', ''preprocessing'', ''visualization'',
  ''model'', ''train'', ''predict'']'
max_df: 0.3
min_df: 5
model: ./models/logreg_regex_graph_v4.sav
nrows: 225565
script_dir: logreg_classifier.ipynb
smooth_idf: true
task: training and evaluation
