C: 100
data: ./data/chunks_10_validate.csv
kernel: linear
label: tag
max_df: 0.3
min_df: 5
model: ./models/svm_regex_graph_v3.sav
nrows: 562
random_state: 241
script_dir: logreg_classifier.ipynb
smooth_idf: true
task: prediction or validation
verbose: 1
