DATASET_PATH: ./data/code_blocks_regex_graph_v2.2.csv
label: preprocessing
max_df: 0.3
min_df: 5
model: ./models/logreg_regex_graph_v2.2.sav
nrows: 226054
script_dir: logreg_classifier.ipynb
smooth_idf: true
