C: 100
data: ./data/code_blocks_unique_regex.csv
kernel: linear
label: preprocessing
max_df: 0.3
min_df: 5
model: ./models/logreg_regex.sav
nrows: 226054
random_state: 241
smooth_idf: true
verbose: 1
